version: "3.4"
services:
  mongodb:
    build:
      context: ./buildmongo #from custom Dockerfile
    restart: always
    volumes:
      - ./mongodb:/data/db

  app:
    build: ./app #from custom Dockerfile
    links:
      - mongodb
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongodb
    env_file:
      - prod.env
