services:
  index:
    build:
      context: .
      dockerfile: Dockerfile
      target: index
    restart: always
    volumes:
      - ./bw_db:/data/
    env_file:
      - prod.env

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
      target: mongo
    restart: always
    volumes:
      - ./bw_db:/data/bw_db
      - ./mongodb:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    links:
      - mongodb
      - index
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongodb
    env_file:
      - prod.env
