services:
  index:
    image: ghcr.io/sourmash-bio/branchwater:index-0.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: index
    restart: always
    volumes:
      - ./bw_db:/data/
    env_file:
      - prod.index.env
    command: >
      /app/bin/branchwater-server
        --port 80
        -k 21
        --scaled 100000
        --location /dev/null
        /data/index

  mongodb:
    image: ghcr.io/sourmash-bio/branchwater:mongo-0.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: mongo
    restart: always
    volumes:
      - ./bw_db:/data/bw_db
      - ./mongodb:/data/db
      - ./metadata:/docker-entrypoint-initdb.d

  app:
    image: ghcr.io/sourmash-bio/branchwater:web-0.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "8001:8000"
    restart: always
    depends_on:
      - mongodb
      - index
    env_file:
      - prod.env
