version: "3.4"
services:
  index:
    build:
      dockerfile: Dockerfile.index
    restart: always
    volumes:
      - ./bw_db:/data/
    env_file:
      - prod.env

  mongodb:
    build:
      context: ./buildmongo #from custom Dockerfile
    restart: always
    volumes:
      - ./bw_db:/data/bw_db
      - ./mongodb:/data/db

  app:
    build: ./app #from custom Dockerfile
    links:
      - mongodb
      - index
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongodb
    env_file:
      - prod.env
