services:
  index:
    build:
      context: .
      dockerfile: Dockerfile
      target: index
    restart: always
    volumes:
      - ./bw_k21:/data/
    env_file:
      - prod.index.env
    command: >
      /app/bin/branchwater-server
        --port 80
        -k 21
        --scaled 100000
        --location /dev/null
        /data/index

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
      target: mongo
    restart: always
    volumes:
      - ./bw_k21:/data/bw_db
      - ./mongodb:/data/db
      - ./metadata:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongodb
      - index
    env_file:
      - prod.env
    command: >
      gunicorn
        --bind 0.0.0.0:8000
        --timeout 120
        --workers 4
        --access-logfile -
        main:app
