[project]
name = "branchwater"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]

[feature.prepare.tasks]
snakemake = { cmd = ["snakemake"] }

[feature.prepare.dependencies]
snakemake = "*"

[environments]
snakemake = ["prepare"]
