[project]
name = "branchwater"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[environments]
default = { features = ["test", "build", "prepare", "deploy", "dev", "web"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }
prepare = { features = ["build", "prepare"], solve-group = "default" }
deploy = { features = ["deploy"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
web = { features = ["web"], solve-group = "default" }

[dependencies]
python = ">=3.12.2,<3.13"

[tasks]
demo = { depends-on = ["index", "metadata"] }

[feature.build.dependencies]
rust = ">=1.80.1,<1.81"
compilers = ">=1.7.0,<1.8"
clangdev = ">=16.0.6,<17.1"
libclang = ">=16.0.6,<17.1"

[feature.build.tasks]
build-server = "cargo build --release -p branchwater-server"

[feature.prepare.tasks]
index = { cmd = ["snakemake"], cwd = "experiments" }
metadata = "docker compose exec mongodb /bin/bash /shell-hook python3 /docker-entrypoint-initdb.d/bqtomongo.py"

[feature.prepare.dependencies]
snakemake = ">=8.5.3,<8.6"
pandas = ">=2.2.1,<2.3"
sourmash = ">=4.8.6,<4.9"
pymongo = "~=4.10"
google-cloud-bigquery = "~=3.26.0"
pyarrow = "*"

[feature.deploy.dependencies]
podman-compose = ">=1.0.6,<1.1"

[feature.deploy.tasks]
deploy = "docker compose"

[feature.test.dependencies]
tox = ">=3.24.5,<4.14"

[feature.test.tasks]
docs = { cmd = ["tox", "-e", "docs"] }

[feature.dev.dependencies]
pyright = "*"

[feature.web.dependencies]
flask = "~=2.3.2"
polars = ">=1.12.0,<2"
pandas = "~=2.0"
pymongo = "~=4.10"
urllib3 = "~=2.0.4"
pyyaml = "~=6.0"
gunicorn = "~=23.0"

[feature.web.pypi-dependencies]
sentry-sdk = { version = "*", extras = ["flask", "pymongo"] }
