[project]
name = "branchwater"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[environments]
prepare = ["prepare"]
deploy = ["deploy"]

[dependencies]

[feature.prepare.tasks]
index = { cmd = ["snakemake"] }
metadata = { cmd = ["podman-compose",
                    "exec", "mongo",
                    "python3", "/docker-entrypoint-initdb.d/bqtomongo.py"] }

[feature.prepare.dependencies]
snakemake = ">=8,<9"

[feature.deploy.dependencies]
podman-compose = "*"
